export const elements = {
  title: document.getElementById("title"),
  homeTab: document.getElementById("home-header"),
  tutorialsTab: document.getElementById("tutorials-header"),
  dataTab: document.getElementById("data-header"),
  practiceTab: document.getElementById("practice-header"),
  homeFooter: document.getElementById("footer-home"),
  tutorialsFooter: document.getElementById("footer-tutorials"),
  dataFooter: document.getElementById("footer-data"),
  practiceFooter: document.getElementById("footer-practice"),
  dateSection: document.getElementById("important-dates"),
  howToSection: document.getElementById("site-howto"),
  introductionSection: document.getElementById("get-to-know"),
  tutorialsIntroSection: document.getElementById("tutorials-intro"),
  tutorialsVideosSection: document.getElementById("tutorials-videos"),
  dataSectionIntro: document.getElementById("data-section-intro"),
  dataLinksUL: document.getElementById("data-links-ul"),
  dataSectionLinks: document.getElementById("data-section-links"),
  dataSubmitted: document.getElementById("data-submitted"),
  dataSectionInput: document.getElementById("data-section-input"),
};
